name 'noip-client'
maintainer 'The Authors'
maintainer_email 'you@example.com'
license 'all_rights'
description 'Installs/Configures noip-client'
long_description 'Installs/Configures noip-client'
version '0.1.0'

depends 'apt'
depends 'build-essential'
